name: bible_test2
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  path_provider: ^0.4.1
  cupertino_icons: ^0.1.2
  sqflite: ^1.2.0
  outline_material_icons: ^0.1.1
  flutter_slidable: ^0.4.9
  xml: "^3.0.0"
  rxdart: ^0.23.0
  share: ^0.6.1+1
  bloc: 3.0.0
  flutter_bloc: ^3.0.0
  equatable: ^1.0.0
  http: ^0.12.0
  intl: any 


  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6

dev_dependencies:
  
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/bible/BibleDb.db
  
  fonts:
    - family: Nanum Gothic
      fonts:
        - asset: assets/fonts/NanumGothic-Regular.ttf
        - asset: assets/fonts/NanumGothic-Bold.ttf
          weight: 700