name: bible_test2
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  path_provider: ^1.5.1 #TODO update
  cupertino_icons: ^0.1.2
  sqflite: ^1.2.0
  outline_material_icons: ^0.1.1
  flutter_slidable: ^0.4.9
  xml: "^3.0.0"
  rxdart: ^0.23.0
  share: ^0.6.3+5 #TODO update
  bloc: 3.0.0
  flutter_bloc: ^3.0.0
  equatable: ^1.0.0
  http: ^0.12.0
  intl: any 
  shared_preferences: ^0.5.6  #TODO update
  hydrated_bloc: ^3.0.0
  json_annotation: ^3.0.1
  font_awesome_flutter: 8.5.0
  flutter_speed_dial: 1.2.5
  url_launcher: ^5.4.1
  flutter_markdown: ^0.3.2
  table_calendar: ^2.2.2
  flutter_auth_buttons: ^0.6.0


  flutter:
    sdk: flutter
  
  #Firebase dependencies
  firebase_analytics: ^5.0.9


  firebase_core: ^0.4.3+2
  firebase_auth: ^0.15.3+1
  cloud_firestore: ^0.13.0+1
  google_sign_in: ^4.1.1

dev_dependencies:
  
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/bible/BibleDb.db
    - assets/bible/NTRecovery.db
    - assets/pictures/lake.png
    - assets/pictures/BTMK_logo.png
    - assets/pictures/glogo.jpg
  
  fonts:
    - family: Nanum Gothic
      fonts:
        - asset: assets/fonts/NanumGothic-Regular.ttf
        - asset: assets/fonts/NanumGothic-Bold.ttf
          weight: 700